spring.application.name=restDemo
server.port = 8001

# H2 Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mvc-project?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# Enable H2 Console
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console